[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14" }
leafwing-input-manager = "0.17.1"
bevy_rapier2d = "0.30.0"
enum-iterator = "2.1.0"
rand = "0.9.2"
